spring.main.web-application-type: NONE

spring.liquibase.change-log: liquibase/changelog_root.yml

spring.datasource.url: jdbc:postgresql://127.0.0.1:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres

spring.jpa.hibernate.ddl-auto: validate

spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.show_sql: true

logging.level.org.springframework.orm.jpa.JpaTransactionManager: DEBUG


by.sakuuj.server.port: 9000