spring.config.import: configtree:${DOCKER_SECRETS_DIR:docker/secrets/}

spring.main.web-application-type: NONE

spring.kafka.bootstrap-servers: ["localhost:10002"]

spring.elasticsearch.uris: ["localhost:9200"]
spring.elasticsearch.connection-timeout: 5s
spring.elasticsearch.socket-timeout: 3s
