name: blogplatform

secrets:
  elastic_search_password:
    file: secrets/spring.elasticsearch.password

services:
  postgres_master:
    container_name: postgres_master_articles
    image: postgres:16.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 127.0.0.1:5432:5432
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1gb

  kafka-broker:
    container_name: kafka-broker-articles
    image: apache/kafka:3.8.0
    hostname: broker_articles
    ports:
      - '10002:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:10002,PLAINTEXT://broker_articles:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker_articles:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_MIN_INSYNC_REPLICAS: 1

  elastic_search:
    secrets:
      - elastic_search_password
    container_name: elasticsearch_articles
    image: elasticsearch:8.14.3
    environment:
      - ELASTIC_PASSWORD_FILE=/run/secrets/elastic_search_password
      - ES_SETTING_DISCOVERY_TYPE=single-node
      - ES_SETTING_XPACK_SECURITY_HTTP_SSL_ENABLED=false
      - ES_SETTING_XPACK_LICENSE_SELF__GENERATED_TYPE=basic
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - net_bp
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - elastic_logs:/usr/share/elasticsearch/logs
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1gb

#  curl -u elastic:elastic -X POST http://localhost:9200/_security/user/kibana_system/_password -d '{"password":"kibana"}' -H 'Content-Type: application/json'
  kibana:
    container_name: kibana_articles
    image: kibana:8.14.3
    environment:
      - ELASTICSEARCH_URL=http://elastic_search:9200
      - ELASTICSEARCH_HOSTS=http://elastic_search:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana
      - XPACK_SECURITY_ENABLED=false
      - XPACK_LICENSE_SELF__GENERATED_TYPE=basic
    ports:
      - 127.0.0.1:5601:5601
    networks:
      - net_bp
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1gb

volumes:
  elastic_data:
  elastic_logs:

networks:
  net_bp:

