server.port: 8080
server.tomcat.threads.max: 8

springdoc.swagger-ui.path: /swagger

spring.aop.proxy-target-class: true

spring.elasticsearch.connection-timeout: 5s
spring.elasticsearch.socket-timeout: 3s

spring.threads.virtual.enabled: true

logging.level.tracer: trace