spring.config:
  import: configtree:${DOCKER_SECRETS_DIR:docker/secrets/}

spring.elasticsearch.uris: ["localhost:9200"]

by.sakuuj.elasticsearch.index-creator.uri: http://${spring.elasticsearch.uris[0]}
by.sakuuj.elasticsearch.index-creator.username: ${spring.elasticsearch.username}
by.sakuuj.elasticsearch.index-creator.password: ${spring.elasticsearch.password}
by.sakuuj.elasticsearch.index-creator.index-to-json-file-pairs:
  - "articles<->elasticsearchQueries/createArticlesIndex.json"
  - "articles2<->elasticsearchQueries/createArticlesIndex.json"

by.sakuuj.elasticsearch.index-creator.enable: false
