server.port: 8080
server.tomcat.threads.max: 8

springdoc.swagger-ui.path: /swagger

spring.aop.proxy-target-class: true
spring.elasticsearch.password: elastic
spring.elasticsearch.username: elastic
spring.threads.virtual.enabled: true

logging.level.tracer: trace