package by.sakuuj.blogsite.article.exception;

public enum ServiceLayerExceptionMessage {

    UPDATE_FAILED_ENTITY_NOT_FOUND,

    OPERATION_FAILED_ENTITY_VERSION_DOES_NOT_MATCH,

    OPERATION_FAILED_INVALID_DTO,

    OPERATION_FAILED_CONSTRAIN_VIOLATION,

    CREATE_FAILED_IDEMPOTENCY_TOKEN_ALREADY_EXISTS,

    OPERATION_FAILED_NOT_FOUND_IN_DATABASE
}
